staging:
  deploy_to: "/var/www/consul"
  ssh_port: "21"
  server: "staging.consul.es"
  user: "xxxxx"

preproduction:
  deploy_to: "/var/www/consul"
  ssh_port: "2222"
  server1: xxx.xxx.xxx.xxx
  server2: xxx.xxx.xxx.xxx
  user: xxxxx

production:
  deploy_to: "/home/deploy/consul"
  ssh_port: "22"
  server1: "18.118.68.198"
  db_server: "localhost"
  user: "deploy"
  server_name: "18.118.68.198"
  full_app_name: "consul"
